# fly.toml file generated for planigo-api on 2023-02-28T16:22:31+01:00

app = "planigo-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  EMAIL_SENDER="welcome@planigo.fr"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443