name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Go 1.14
          uses: actions/setup-go@v3
          with:
              go-version: 1.19
              cache: true
        - name: Install dependencies
          run: go get .
        - name: Build
          run: go build -v
        - name: Test
          run: go test -v